#!/bin/bash
socket=/etc/systemd/system/systemd-journald-audit.socket
if [ -e "$socket" -a -h "$socket" ];then
    destination=$(readlink -f $socket)
    if [ "x$destination" != "x/dev/null" ]; then
        dpkg-reconfigure lliurex-journald-settings
    fi
fi
exit 0
